export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const DATA_LOADING = "DATA_LOADING";
export const LOADING_DONE = "LOADING_DONE";

export const USERLOGIN_MODAL_TOGGLE = "USER_MODAL_TOGGLE";
export const USERLOGIN_MODAL_OPEN = "USER_MODAL_OPEN";
export const USERLOGIN_MODAL_CLOSE = "USER_MODAL_CLOSE";

export const TEAMLOGIN_MODAL_TOGGLE = "TEAM_MODAL_TOGGLE";
export const TEAMLOGIN_MODAL_OPEN = "TEAM_MODAL_OPEN";
export const TEAMLOGIN_MODAL_CLOSE = "TEAM_MODAL_CLOSE";

export const PROFILE_MODAL_TOGGLE = "PROFILE_MODAL_TOGGLE";
export const PROFILE_MODAL_OPEN = "PROFILE_MODAL_OPEN";
export const PROFILE_MODAL_CLOSE = "PROFILE_MODAL_CLOSE";

export const GET_ALL_CLIENTAPP = "GET_ALL_CLIENTAPP";
export const SET_TEAM_MEMBERS = "SET_TEAM_MEMBERS";

export const LOADING = "LOADING";
