export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const DATA_LOADING = "DATA_LOADING";
export const LOADING_DONE = "LOADING_DONE";

export const USERLOGIN_MODAL_TOGGLE = "USER_MODAL_TOGGLE";
export const USERLOGIN_MODAL_OPEN = "USER_MODAL_OPEN";
export const USERLOGIN_MODAL_CLOSE = "USER_MODAL_CLOSE";

export const TEAMLOGIN_MODAL_TOGGLE = "TEAM_MODAL_TOGGLE";
export const TEAMLOGIN_MODAL_OPEN = "TEAM_MODAL_OPEN";
export const TEAMLOGIN_MODAL_CLOSE = "TEAM_MODAL_CLOSE";

export const PROFILE_MODAL_TOGGLE = "PROFILE_MODAL_TOGGLE";
export const PROFILE_MODAL_OPEN = "PROFILE_MODAL_OPEN";
export const PROFILE_MODAL_CLOSE = "PROFILE_MODAL_CLOSE";

export const ADD_APPOINTMENT_MODAL_TOGGLE = "ADD_APPOINTMENT_MODAL_TOGGLE";
export const ADD_APPOINTMENT_MODAL_OPEN = "ADD_APPOINTMENT_MODAL_OPEN";
export const ADD_APPOINTMENT_MODAL_CLOSE = "ADD_APPOINTMENT_MODAL_CLOSE";

export const DELETE_MODAL_TOGGLE = "DELETE_MODAL_TOGGLE";
export const DELETE_MODAL_OPEN = "DELETE_MODAL_OPEN";
export const DELETE_MODAL_CLOSE = "DELETE_MODAL_CLOSE";

export const GET_ALL_CLIENTAPP = "GET_ALL_CLIENTAPP";
export const SET_USER_APPS = "SET_USER_APPS";
export const SET_TEAM_MEMBERS = "SET_TEAM_MEMBERS";

export const GET_APPBY_TEAMID = "GET_APPBY_TEAMID";
export const GET_APPBY_DATE_ID = "GET_APPBY_DATE_ID";

export const GET_ALL_CLIENTS = "GET_ALL_CLIENTS";

export const GET_ALL_TEAMAPP = "GET_ALL_TEAMAPP";
export const GET_ALL_TEAMADMIN = "GET_ALL_TEAMADMIN";

export const MESSAGE = "MESSAGE";

export const SET_APP_JUSTMADE = "SET_APP_JUSTMADE";

export const LOADING = "LOADING";
